export const countries = [
  { code: "US", name: "United States",   dial: "1" },
  { code: "GB", name: "United Kingdom",  dial: "44" },
  { code: "SA", name: "Saudi Arabia",    dial: "966" },
  { code: "AE", name: "UAE",             dial: "971" },
  { code: "EG", name: "Egypt",           dial: "20" },
  { code: "IN", name: "India",           dial: "91" },
  { code: "PK", name: "Pakistan",        dial: "92" },
  { code: "ID", name: "Indonesia",       dial: "62" },
  { code: "BR", name: "Brazil",          dial: "55" },
  { code: "MX", name: "Mexico",          dial: "52" },
  { code: "DE", name: "Germany",         dial: "49" },
  { code: "FR", name: "France",          dial: "33" },
  { code: "ES", name: "Spain",           dial: "34" },
  { code: "IT", name: "Italy",           dial: "39" },
  { code: "TR", name: "Turkey",          dial: "90" },
  { code: "RU", name: "Russia",          dial: "7" },
  { code: "CN", name: "China",           dial: "86" },
  { code: "JP", name: "Japan",           dial: "81" },
  { code: "KR", name: "South Korea",     dial: "82" },
  { code: "NG", name: "Nigeria",         dial: "234" },
  { code: "KE", name: "Kenya",           dial: "254" },
  { code: "ZA", name: "South Africa",    dial: "27" },
  { code: "MA", name: "Morocco",         dial: "212" },
  { code: "DZ", name: "Algeria",         dial: "213" },
  { code: "IQ", name: "Iraq",            dial: "964" },
  { code: "JO", name: "Jordan",          dial: "962" },
  { code: "LB", name: "Lebanon",         dial: "961" },
  { code: "KW", name: "Kuwait",          dial: "965" },
  { code: "QA", name: "Qatar",           dial: "974" },
  { code: "BH", name: "Bahrain",         dial: "973" },
  { code: "OM", name: "Oman",            dial: "968" },
  { code: "PH", name: "Philippines",     dial: "63" },
  { code: "MY", name: "Malaysia",        dial: "60" },
  { code: "TH", name: "Thailand",        dial: "66" },
  { code: "AU", name: "Australia",       dial: "61" },
  { code: "CA", name: "Canada",          dial: "1" },
];
